service: quotes-api


package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

  environment:
    quotesTableName: quotes
    policiesTableName: policies
    dogBreedsTableName: breeds_dog
    catBreedsTableName: breeds_cat

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  search:
    handler: search.main
    events:
      - http:
          method: post
          path: /
          cors: true
  policies:
    handler: listPolicies.main
    events:
      - http:
          method: get
          path: /policies
          cors: true


resources:
  - ${file(resources/api-gateway-errors.yml)}